---
# Octoprint service endpoint
apiVersion: v1
kind: Service
metadata:
  name: octoprint-service-endpoint
spec:
  type: ExternalName
  externalName: octoprint.octoprint.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab
  labels:
    app.kubernetes.io/name: lab
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
spec:
  ingressClassName: cilium
  rules:
  - host: lab.idkthisisademo.lol
    http:
      paths:
      - pathType: Prefix
        path: "/octoprint"
        backend:
          service:
            name: octoprint-service-endpoint
            port: 
              number: 80
  tls:
  - hosts:
    - lab.idkthisisademo.lol
    secretName: lab-tls
