apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
  namespace: external-secrets
spec:
  secretName: bitwarden-tls-certs
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: bitwarden-sdk-server.external-secrets.svc.cluster.local
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
  usages:
    - server auth
    - client auth
  isCA: true
