$ANSIBLE_VAULT;1.1;AES256
38303130363932616632633566383533306162373637636439316165333637356535316633363537
6238366665373630386166626564313734643338366332610a623664383930366164386237313563
30626639393865616231306436393539313133333333346466303662643364653061363062306130
3961313039386331340a653930613834313130376265373631613565393833363130343561653964
36663139353035393832383732663731376463636536613866356333663137363765366637616163
3061353831663131623134643639323536396466376133616231
