apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octoprint-pvc
spec:
  resources:
    requests:
      storage: 5G
  volumeMode: Filesystem
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce