apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vcluster-platform

helmCharts:
  - name: vcluster-platform
    repo: https://charts.loft.sh
    version: 4.6.1
    releaseName: vcluster-platform
    valuesFile: values.yaml

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: vcluster-platform-ingress
