admin:
  create: true
  username: admin
  password: password

ingress:
  enabled: true
  host: vcluster.idkthisisademo.lol
  name: vcluster-platform-ingress
  ingressClass: cilium
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    io.cilium.ingress/websocket: "enabled"
  tls:
    enabled: true
    secretName: vcluster-platform-tls

audit:
  enableSideCar: true
  level: 1

config:
  loftHost: "https://vcluster.idkthisisademo.lol"
